name: Publish NuGet package

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore /p:PublicRelease=true

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1
        id: login
        with:
          user: meenzen

      - name: NuGet push
        run: dotnet nuget push "src/*/bin/Release/*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --skip-duplicate --source https://api.nuget.org/v3/index.json
